name: story_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  shared_preferences: ^2.2.2
  provider: ^6.1.1 
  http: ^1.2.0
  image_picker: ^1.0.7
  image_picker_windows: ^0.2.1+1
  camera: ^0.10.0+1
  camera_windows: ^0.2.1+1
  image: ^4.1.7
  animated_splash_screen: ^1.3.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  google_maps_flutter: ^2.5.3
  google_maps_flutter_web: ^0.5.4+3
  location: ^5.0.3
  geocoding: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.1.2
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
